default_language_version:
  python: python3.8
repos:
  - hooks:
      - id: black
        language_version: python3.8
    repo: https://github.com/ambv/black
    rev: 21.4b2
  - hooks:
      - id: flake8
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1