language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
install: pip3 install pytest -r requirements/production.txt
# command to run tests
script: pytest