"""empty message

Revision ID: 516ff6933e39
Revises: ff1d1d2b820d
Create Date: 2021-05-04 15:25:34.273854

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "516ff6933e39"
down_revision = "ff1d1d2b820d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("slug", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "slug")
    # ### end Alembic commands ###
