"""empty message

Revision ID: 53ceac12ff90
Revises: 516ff6933e39
Create Date: 2021-05-09 13:37:35.869550

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "53ceac12ff90"
down_revision = "ff1d1d2b820d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("description", sa.String(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "description")
    # ### end Alembic commands ###
