"""empty message

Revision ID: d1505efe82ed
Revises:
Create Date: 2021-04-28 12:48:14.592021

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1505efe82ed"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.cast(1, sa.BOOLEAN()),
            nullable=False,
        ),
        sa.Column("password", sa.String(), server_default="", nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("photo", sa.String(), nullable=True),
        sa.Column("mobile", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), server_default="", nullable=False),
        sa.Column("last_name", sa.String(), server_default="", nullable=False),
        sa.Column("first_name_ar", sa.String(), server_default="", nullable=False),
        sa.Column("last_name_ar", sa.String(), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("role_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
